### PR TITLE
Updated the SimMetrics somewhat

### PR DESCRIPTION
**Pull request by mpkorstanje**
Hey, I noticed you're still using the old version. I've updated and upgraded it a bit. Killed a bucket of bugs, put it on maven central too. Might wanna use my version.

### CODE REVIEW

**Comment by saulvargas** [comment]
Wow, thanks a lot @mpkorstanje! I'll take a look at your code in the following days. If it is compatible with the projects in which I am using the library, most surely I will directly use the maven. I forked an mavenized the old version just so the project could be used with jitpack.io

**Comment by mpkorstanje** [comment]
I just managed to get into contact with the owner of [Simmetrics](https://github.com/Simmetrics/simmetrics) again. We've merged all my changes into that. Using that one is probably better. As the project is on Maven Central I think you can do without jitpack. Just include the dependency.

Compatibility, well that is a difficult one. The algorithms should mostly work the same, but structurally I had to change a bucket of things to whip this library into shape.

Most changes shouldn't be too difficult though. [StringMetrics](https://github.com/Simmetrics/simmetrics/blob/master/simmetrics-core/src/main/java/org/simmetrics/StringMetrics.java) contains most of the metrics as they were originally. I did leave out the really crappy ones.

If you need any help converting stuff or solving issues, I'd be happy to help but its your choice of course.

**Comment by saulvargas** [comment]
Hi again,

I just adapted my projects to be compatible with the version available in Maven central. As a consequence, I will not update this fork and delete it in the following days.

Thanks a lot!

**Comment by mpkorstanje** [comment]
You're welcome!

**Pull request closed without merging**
